twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /cmd_vel
        timeout : 0.5
        priority: 10
      pmzbsavy_ik_navigation:
        topic   : /diff_drive_pmzbsavy
        timeout : 0.5
        priority: 15
      pmzbsavy_navigation:
        topic   : /cmd_vel_pmzbsavy
        timeout : 0.5
        priority: 20
      nav_navigation:
        topic   : /cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 100