twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /cmd_vel
        timeout : 0.5
        priority: 10
      zhbbot_ik_navigation:
        topic   : /diff_drive_zhbbot
        timeout : 0.5
        priority: 15
      zhbbot_navigation:
        topic   : /cmd_vel_zhbbot
        timeout : 0.5
        priority: 20
      nav_navigation:
        topic   : /cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 100