controller_manager:
  ros__parameters:

    use_sim_time: true
    
    # If x4 Simulator is used, update_rate is 250 Hz
    # update_rate: 250 # Hz
    # If x8 Simulator is used, update_rate is 125 Hz
    # update_rate: 125 # Hz
    # If x10 Simulator is used, update_rate is 125 Hz
    update_rate: 100 # Hz

    # update_rate: 1000 # Hz

    # x2 Simulator
    # update_rate: 500 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_cont:
      type: velocity_controllers/JointGroupVelocityController

velocity_cont:
  ros__parameters:

    joints:
      - left_wheel_joint
      - right_wheel_joint

    command_interfaces:
      - velocity
    
    state_interfaces:
      - velocity
      - effort