<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- This file is not a robot in and of itself, it just contains some useful tags that could be included in any robot -->

    <!-- add more codes -->
    <material name="grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.5 1.0 1.0"/>      
    </material>

    <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>      
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 0.6"/>      
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>      
    </material>

    <material name="darkblue">
        <color rgba="0.0 0.0 0.3764 0.6"/>      
    </material>

    <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
    </xacro:macro>

  <xacro:macro name="carverabwu_common">
    <!-- Mobile Robot Parameter -->
    <xacro:property name="chassis_length" value="0.8" scope="parent"/>
    <xacro:property name="chassis_width" value="0.5" scope="parent"/>
    <xacro:property name="chassis_height" value="0.138" scope="parent"/>
    <xacro:property name="chassis_mass" value="1.0" scope="parent"/>
    <xacro:property name="wheel_radius" value="0.075" scope="parent"/>
    <xacro:property name="wheel_thickness" value="0.026" scope="parent"/>
    <xacro:property name="wheel_mass" value="50" scope="parent"/>
    <xacro:property name="wheel_offset_x" value="0.4" scope="parent"/>
    <xacro:property name="wheel_offset_y" value="0.2" scope="parent"/>
    <xacro:property name="wheel_offset_z" value="0.0001" scope="parent"/>
    <xacro:property name="caster_wheel_radius" value="0.05" scope="parent"/>
    <xacro:property name="caster_wheel_mass" value="0.01" scope="parent"/>
    <xacro:property name="caster_wheel_offset_x" value="0.3" scope="parent"/>
    <xacro:property name="caster_wheel_offset_y" value="0.2" scope="parent"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}" scope="parent"/>
  </xacro:macro>

</robot>