<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="pmzbsavy_core" params="">

        <xacro:include filename="inertial_macros.xacro" />

        <xacro:include filename="pmzbsavy_common.xacro" />
        <xacro:pmzbsavy_common/>

        <xacro:include filename="pmzbsavy_ros2control.xacro" />
        <xacro:pmzbsavy_control/>

        <!-- BASE LINK -->

        <link name="base_link">
            <visual>
                <geometry>
                    <box size="0.01 0.01 0.01"/>
                </geometry>
                <material name="Cyan">
                    <color rgba="0 1.0 1.0 1.0"/>
                </material>
            </visual>
        </link>

        <!-- BASE_FOOTPRINT LINK -->

        <!-- For Differantial Drive Controller -->
        <joint name="base_footprint_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0 0 -0.05" rpy="0 0 0"/>
        </joint>

        <link name="base_footprint">
        </link>

        <!-- CHASSIS Information -->
       
        <joint name="chassis_joint" type="fixed">
            <parent link="base_link"/>
            <child link="chassis"/>
            <origin xyz="0 0 0"/>
        </joint>
        
        <link name="chassis">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry>
                    <mesh filename="file://$(find pmzbsavy_description)/meshes/URDF_SAVVY.STL"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <collision>
                <origin xyz="0.03595 -0.00002 0.2385"/>
                <geometry>
                    <box size="0.558 0.4876 0.295"/>
                </geometry>
            </collision>
            <xacro:inertial_box mass="38.3" x="0.516" y="0.4876" z="0.295">
            <origin xyz="0.0 0.0 0.2335" rpy="0 0 0"/>
            </xacro:inertial_box>
            
        </link>
        
        <!-- LEFT WHEEL -->

        <joint name="left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${(wheel_thickness/2) + 0.105525} 0" rpy="-${pi/2} 0 0" />
            <axis xyz="0 0 1"/>
        </joint>

        <link name="left_wheel">
        <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="left_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- RIGHT WHEEL -->

        <joint name="right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="right_wheel"/>
            <origin xyz="0 -${(wheel_thickness/2) + 0.105525} 0" rpy="${pi/2} 0 0" />
            <axis xyz="0 0 -1"/>
        </joint>

        <link name="right_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="right_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- CASTER WHEEL FONT RIGHT -->

        <joint name="caster_wheel_f_r_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_f_r"/>
            <origin xyz="0.20490726 -0.135475 0.0001" rpy="0 0 0"/>
        </joint>

        <link name="caster_wheel_f_r">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_f_r">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL FONT LEFT -->
        <joint name="caster_wheel_f_l_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_f_l"/>
            <origin xyz="0.20490726 0.135475 0.0001" rpy="0 0 0"/>
        </joint>

        <link name="caster_wheel_f_l">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>
        
        <gazebo reference="caster_wheel_f_l">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL BACK RIGHT -->
        <joint name="caster_wheel_r_r_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_r_r"/>
            <origin xyz="-0.14804637 -0.135475 0.0001" rpy="0 0 0"/>
        </joint>

        <link name="caster_wheel_r_r">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_r_r">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

        <!-- CASTER WHEEL BACK LEFT -->
        <joint name="caster_wheel_r_l_joint" type="fixed">
            <parent link="base_link"/>
            <child link="caster_wheel_r_l"/>
            <origin xyz="-0.14804637 0.135475 0.0001" rpy="0 0 0"/>
        </joint>

        <link name="caster_wheel_r_l">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>

        <gazebo reference="caster_wheel_r_l">
            <material>Gazebo/Blue</material>
            <mu1 value="0.001"/>
            <mu2 value="0.001"/>
        </gazebo>

    </xacro:macro>

</robot>