SensorGlobal:
  TIMER_FREQUENCY: 10
  IMU_TOPIC_NAME: "/IMU"
  WHEEL_LEFT_VELOCITY_TOPIC_NAME: "wheelL_vel"
  WHEEL_RIGHT_VELOCITY_TOPIC_NAME: "wheelR_vel"

  IMU_CALIBRATION_FILE : "calibration/imu_calibration_result.yaml"
  WHEEL_VELOCITY_CALIBRATION_FILE : "calibration/wheel_velocity_calibration_result.yaml"

carversavvyRosBridge:

  # Robot Parameters
  WHEEL_RADIUS: 0.050
  BASE_WIDTH: 0.270

  # ROS Topics
  IMU_PUB_TOPIC_NAME: "/carversavvy_ros/imu"
  WHEEL_ODOMETRY_PUB_TOPIC_NAME: "/carversavvy_ros/wheel_odom"

  # Frame Calulations parameters
  IMU_FRAME_ID: "imu_link"
  ODOM_FRAME_ID: "odom"
  BASE_FRAME_ID: "base_link"

carversavvyCalibrationSensor:

  MAX_CALIBRATION_ITERATIONS: 1000

  NODE_CALIBRATION_SERVICE_NAME: "carversavvy_begin_calibration"
