ObstacleParams:
  NumObstacles: 4
  obstacleNames: ["cylinder_obstacle_1", "cylinder_obstacle_2", "cylinder_obstacle_3", "cylinder_obstacle_4"]
  ObstacleTypes: ["cylinder"]
  ObstacleRadii: [0.5, 0.5, 0.25, 0.25]
  ObstacleHeights: [0.5, 0.5, 0.5, 0.5]
  ObstacleColors: ["blue", "red", "green", "yellow"]

cylinder_obstacle_1:
  InitialPose: [5.50, 6.00, 0.50]
  TargetPose: [-5.50, 6.00 , 0.50]

cylinder_obstacle_2:
  InitialPose: [-6.0, -4.00, 0.50]
  TargetPose: [2.0, -4.00, 0.50]

cylinder_obstacle_3:
  InitialPose: [-5.5 , 3.5, 0.50]
  TargetPose: [3.0, -6.00 , 0.50]

cylinder_obstacle_4:
  InitialPose: [0, -6.50, 0.50]
  TargetPose: [0, 2.00 , 0.50]


