ObstacleParams:
  NumObstacles: 4
  obstacleNames: ["cylinder_obstacle_1", "cylinder_obstacle_2", "cylinder_obstacle_3", "cylinder_obstacle_4"]
  ObstacleTypes: ["cylinder"]
  ObstacleRadii: [0.5, 0.5, 0.25, 0.25]
  ObstacleHeights: [0.5, 0.5, 0.5, 0.5]
  ObstacleColors: ["blue", "red", "green", "yellow"]

cylinder_obstacle_1:
  InitialPose: [-8.0 ,-8.0, 0.50]
  TargetPose: [-8.00, -2.00 , 0.50]

cylinder_obstacle_2:
  InitialPose: [0.0 ,-8.0, 0.50]
  TargetPose: [0.0, 3.00, 0.50]

cylinder_obstacle_3:
  InitialPose: [9.0 ,9.0, 0.50]
  TargetPose: [-6.5, -6.00 , 0.50]

cylinder_obstacle_4:
  InitialPose: [-8.0 ,8.0, 0.50]
  TargetPose: [2.0, 8.0 , 0.50]
