ObstacleParams:
  NumObstacles: 2
  obstacleNames: ["cylinder_obstacle_1", "cylinder_obstacle_2"]
  ObstacleTypes: ["cylinder"]
  ObstacleRadii: [0.5, 0.5]
  ObstacleHeights: [0.5, 0.5]
  ObstacleColors: ["blue", "red"]

cylinder_obstacle_1:
  InitialPose:  [3.0, 5.0, 0.50]
  TargetPose:   [-5.0, 5.0, 0.50]

cylinder_obstacle_2:
  InitialPose:  [3.0, -5.0, 0.50]
  TargetPose:   [-5.0, -5.0, 0.50]


